#ifndef __SKILL_STATEDEF_H__
#define __SKILL_STATEDEF_H__

namespace GNET
{
enum visible_state{
	// ?????
	VSTATE_BLESSED     = 1,  // ???????
	VSTATE_CURSED      = 2,  // ???????
	VSTATE_RETORT      = 3,  // ????
	VSTATE_SLOW        = 4,  // ????
	VSTATE_DIZZY       = 5,  // ????
	VSTATE_SLEEP       = 6,  // ???
	VSTATE_FIX         = 7,  // ????
	VSTATE_SEALED      = 8,  // ???, ???????
	VSTATE_INFAUST     = 9,  // ????, ????????
	VSTATE_THUNDER     = 10, // ???, ???????????
	VSTATE_TOXIC       = 11, // ?ж?
	VSTATE_BURNING     = 12, // ???, ???????????
	VSTATE_FALLEN      = 13, // ???
	VSTATE_BLEEDING    = 14, // ???
	VSTATE_MAGICLEAK   = 15, // h?????
	VSTATE_ICEBLADE    = 16, // ???
	VSTATE_POWERUP     = 17, // ????
	VSTATE_FIREBLADE   = 18, // ????????
	VSTATE_FLOWER1     = 19, // ???1
	VSTATE_FLOWER2     = 20, // ???2
	VSTATE_FLOWER3     = 21, // ???3
	VSTATE_FLOWER4     = 22, // ???4
	VSTATE_NOREGAIN    = 23, // ????????????
	// ???????
	VSTATE_FIRESHIELD  = 24, // ??????
	VSTATE_ICESHIELD   = 25, // ????????
	VSTATE_SOILSHIELD  = 26, // ???????
	VSTATE_ANTIWATER   = 27, // ?????
	// ????????
	VSTATE_FEATHERSHIELD = 28, // ????
	// ??a????
	VSTATE_WINGSHIELD  = 29, // ????
	VSTATE_FIREARROW   = 30, // ??????
	// ????????
	VSTATE_JINGJI      = 31, // ??????
	VSTATE_FOXFORM     = 32, // ??????
	// ????????
	VSTATE_BLIND         = 33, // ?a

	VSTATE_IMMUNESEALED = 34,	//??????//lgc
	VSTATE_IMMUNESLEEP 	= 35,	//???????
	VSTATE_IMMUNEFIRE 	= 36,	//??????
	VSTATE_IMMUNEWATER 	= 37,	//?????
	VSTATE_IMMUNEMETAL 	= 38,	//??????
	VSTATE_IMMUNEWOOD 	= 39,	//l????
	
	VSTATE_IMMUNESOIL 	= 40,	//??????
	VSTATE_WINDSHIELD  	= 41,	//??????
	VSTATE_AIRSTREAMLOCK= 42,	//??????
	VSTATE_WEAKELEMENT 	= 43,	//???????
	VSTATE_IMMUNEWEAK	= 44,	//???????????
	VSTATE_BEFROZEN 	= 45,	//????
	VSTATE_VACUUM 		= 46,	//????
	VSTATE_WATERFIREARMOR = 47,	//?????
	
	VSTATE_FSSTAR 		= 48,	//??????
	VSTATE_INVINCIBLE 	= 49,	//??? //??????????????? cgame/gs/invincible_filter.cpp
	VSTATE_APGENCONT 	= 50,	//???????????
	VSTATE_APLEAKCONT 	= 51,	//???????????
	VSTATE_ADDATTACKDEGREE 		= 52,	//???????????
	VSTATE_ADDDEFENCEDEGREE 	= 53,	//???????????
	VSTATE_ABSORBPHYSICDAMAGE 	= 54,	//???????????
	VSTATE_ABSORBMAGICDAMAGE 	= 55,	//??????????
	
	VSTATE_IMMUNEBLOODING		= 56,	//???????
	VSTATE_HARDENSKIN			= 57,	//????
	VSTATE_INVISIBLE			= 58,	//????//??????????????? cgame/gs/invisible_filter.cpp
	VSTATE_SOULRETORT			= 59,	//???????
	VSTATE_SOULSEALED			= 60,	//??????
	VSTATE_SOULBEATBACK			= 61,	//???????
	VSTATE_SOULSTUN				= 62,	//???????
	VSTATE_HURTWHENUSESKILL		= 63,	//??u?????????

	VSTATE_INCDEBUFFDODGE		= 64,	//??????
	VSTATE_INCDAMAGEDODGE		= 65,	//???????
	VSTATE_ADJUSTATTACKDEFEND1	= 66,	//???????
	VSTATE_ADJUSTATTACKDEFEND2	= 67,	//???????
	VSTATE_DEEPICETHRUST		= 68,	//???????
	VSTATE_ATTACKATTACHSTATE1	= 69,	//???????????????1 //Fogo
	VSTATE_ATTACKATTACHSTATE2	= 70,	//???????????????2 //Gelo
	VSTATE_ATTACKATTACHSTATE3	= 71,	//???????????????3 //Madeira	

	VSTATE_BLADESHADOW			= 72,	//??????
	VSTATE_CONSECRATION 		= 73,	//??? // Terra
	VSTATE_POISIONSEED			= 74,	//????
	VSTATE_HPGENSEED			= 75,	//?????
	VSTATE_INCWOODWATERDEFENSE 	= 76,	//????l????? 
	VSTATE_SPECIALSLOW			= 77,	//????l????
	VSTATE_TRANSPORTMPTOPET 	= 78,	//????????????mp
	VSTATE_FASTPRAYINCMAGIC 	= 79,	//??????????????
	
	VSTATE_INCDEFENCESMITE 		= 80,	//????????????
	VSTATE_INCRESISTMAGIC 		= 81,	//???????????
	VSTATE_TRANSPORTDAMAGETOPET = 82,	//???????(????)???????
	VSTATE_ABSORBDAMAGEINCDEFENSE = 83,	//???????????
	VSTATE_CHANCEOFREBIRTH		= 84,	//??l??
	VSTATE_INCCOUNTEDSMITE		= 85,	//????????(????Ч????)
	VSTATE_ATTACKATTACHSTATE4	= 86,	//???????????????4 // Metal	
	VSTATE_ARENARED				= 87,	// Arena Red
	VSTATE_ARENABLUE			= 88,	// Arena Blue
	VSTATE_SHURA3				= 89,	//?????
	VSTATE_SHURA4				= 90,	//?????
	VSTATE_POSITIONROLLBACK		= 91,
	VSTATE_HPROLLBACK			= 92,
	VSTATE_NOCHANGESELECT		= 93,
	VSTATE_HEALABSORB			= 94,
	VSTATE_REPELONNORMALATTACK	= 95,
	VSTATE_DECCRITRESISTANCE	= 96,
	VSTATE_TRANSMITSKILLATTACK	= 97,
	VSTATE_ADDITIONALATTACK		= 98,
	VSTATE_FORBIDBESELECTED		= 99,
	VSTATE_DELAYEARTHHURT		= 100,
	VSTATE_DIZZYINCHURT			= 101,
	VSTATE_SOULRETORT2			= 102,
	VSTATE_FIXONDAMAGE			= 103,
	VSTATE_INCATTACKONDAMAGE	= 104,
	VSTATE_REBIRTH2				= 105,
	VSTATE_HEALSTEAL			= 106,
	VSTATE_DROPMONEYONDEATH		= 107,
	VSTATE_INCATTACKRANGE		= 108,
	VSTATE_INVINCIBLE5			= 109,
	VSTATE_THUNDERFORM			= 110,
	VSTATE_BLADEAURA			= 111,
	VSTATE_YJDANCE				= 112,
	VSTATE_FSICEWORLD			= 113,
	VSTATE_FLAGER				= 114,	//???????
	VSTATE_DOG					= 115,
	VSTATE_SNAKE				= 116,
	VSTATE_PALSY				= 117,	//???????????
	VSTATE_MODIFYSPECSKILLPRAY	= 118,	
	VSTATE_INCSPECSKILLDAMAGE	= 119,	
	VSTATE_HEALSHIELD			= 120,
	VSTATE_INCFLYSPEED			= 121,
	VSTATE_MOVEPUNISH			= 122,
	VSTATE_STANDPUNISH			= 123,
	VSTATE_STANDPUNISH2			= 124,
	VSTATE_CHANTSHIELD			= 125,
	VSTATE_INTERVALPALSY		= 126,
	VSTATE_HUNTERSOUL			= 127,
	VSTATE_WHITE1				= 128,
	VSTATE_WHITE2				= 129,
	VSTATE_WHITE3				= 130,
	VSTATE_BLACK1				= 131,
	VSTATE_BLACK2				= 132,
	VSTATE_BLACK3				= 133,
	VSTATE_WHITE1BLACK1			= 134,
	VSTATE_WHITE1BLACK2			= 135,
	VSTATE_WHITE2BLACK1			= 136,
	VSTATE_INTERNALINJURY		= 137,
	VSTATE_DEATHRESETCD			= 138,
	VSTATE_APPENDDAMAGE			= 139,
	VSTATE_COOLDOWNPUNISH		= 140,
	VSTATE_SKILL2772			= 141,
	VSTATE_DETAINDART           = 142,
    VSTATE_EXTRAEXPFACTOR       = 143,

	VSTATE_NEWBUFF1			    = 144, // N/A
	VSTATE_NEWBUFF2			    = 145, // N/A
	VSTATE_NEWBUFF3			    = 146, // N/A

	VSTATE_ACCUMULATEATTACK		= 147, // UltWR
	VSTATE_ACCUMULATEATTACK2	= 148, // UltWR
	VSTATE_INCPLUSMAXHP     	= 149, //ULTEP
	VSTATE_DECSOUL    			= 150, //ULTESP
	VSTATE_DEBITHURT			= 151, //G17
	VSTATE_NEWBUFF9			    = 152, // Simbolo vermelho na cabeca
	VSTATE_NEWBUFF10			= 153, // Queimacao verde no personagem
	VSTATE_DECFARDMG    		= 154, //ULTRT

	VSTATE_NEWBUFF12		 	= 155, // Efeito verde giratorio
	VSTATE_NEWBUFF13			= 156, // Agua no chao em circulo
	VSTATE_NEWBUFF14			= 157, // Raio amarelo
	VSTATE_NEWBUFF15			= 158, // Congelamento grande
	VSTATE_NEWBUFF16			= 159, // Trofel na cabeca
	VSTATE_NEWBUFF17			= 160, // Arco Iris LGBT
	VSTATE_NEWBUFF18			= 161, // Cogumelo gigante amarelo
	VSTATE_NEWBUFF19			= 162, // Cogumelo gigante azul
	VSTATE_NEWBUFF20			= 163, // Contagem regressiva (10segundos)
	VSTATE_NEWBUFF21			= 164, // Coroa de anjo na cabeca
	VSTATE_NEWBUFF22			= 165, // Asa Branca
	VSTATE_NEWBUFF23			= 166, // Asa Preta nas costas
	VSTATE_NEWBUFF24			= 167, // Olho vermelho na cabeca
	VSTATE_NEWBUFF25			= 168, // Efeito vermelho no chao, com furacao no personagem
	VSTATE_NEWBUFF26			= 169, // Estrelas piscando e efeito no chao
	VSTATE_NEWBUFF27			= 170, // Bichinho legal amarelo
	VSTATE_NEWBUFF28			= 171, // Ursinho voador
	VSTATE_NEWBUFF29			= 172, // Dragao azul
	VSTATE_NEWBUFF30			= 173, // Contagem 10 Segundos
	VSTATE_NEWBUFF31			= 174, // Efeitos chineses em giro
	VSTATE_NEWBUFF32			= 175, // Efeito varias ondas ao lado do personagem (Branca) // Ulti Atiradora
	VSTATE_NEWBUFF33			= 176, // Efeito varias ondas ao lado do personagem (Preta) // Ulti Atiradora
	VSTATE_NEWBUFF34			= 177, // Penas na cabeca
	VSTATE_NEWBUFF35			= 178, // N/A
	VSTATE_NEWBUFF36			= 179, // Asa Preta do Paladino
	VSTATE_NEWBUFF37			= 180, // Efeito do Escudo de Defesa ( Escudo Amarelo )
	VSTATE_NEWBUFF38			= 181, // Efeito do Escudo de Ataque ( Espada vermelha na cabeca )
	VSTATE_NEWBUFF39			= 182, // Efeito do Escudo de borrao ( Amarelo )
	VSTATE_NEWBUFF40			= 183, // Efeito preto e vermelho chao e cabeca do char
	VSTATE_NEWBUFF41			= 184, // Globo Gigante ( Branco )
	VSTATE_NEWBUFF42			= 185, // Espada Preta na Cabeca
	VSTATE_NEWBUFF43			= 186, // Raios no chao conectando ao char
	VSTATE_NEWBUFF44			= 187, // N/A
	VSTATE_NEWBUFF45			= 188, // Globo Gigante ( Branco )
	VSTATE_NEWBUFF46			= 189, // Efeito do Escudo de borrao ( Preto ) -- Borrao
	VSTATE_NEWBUFF47			= 190, // N/A
	VSTATE_NEWBUFF48			= 191, // N/A	
	
	VSTATE_NEWBUFF49			= 192, // Asa Preta do Paladino

	VSTATE_NEWBUFF50			= 193, // Rosas Nascendo no chao enquanto anda
	VSTATE_NEWBUFF51			= 194, // Porcos de com moedas no chao enquanto anda
	VSTATE_NEWBUFF52			= 195, // N/A
	VSTATE_NEWBUFF53			= 196, // N/A
	VSTATE_NEWBUFF54			= 197, // Efera do Parque em torno do personagem
	VSTATE_NEWBUFF55			= 198, // Esfera vermelha e azul em torno do personagem com alados nascendo em torno
	VSTATE_NEWBUFF56			= 199, // Asa colorida nas costas
	VSTATE_NEWBUFF57			= 200, // NPC Angel no Ombro
	VSTATE_NEWBUFF58			= 201, // NPC Demon no Ombro
	VSTATE_NEWBUFF59			= 202, // NPC Guarda no Ombro 
	VSTATE_NEWBUFF60			= 203, // NPC do Wallpaper no Ombro 
	VSTATE_NEWBUFF61			= 204, // Efeito de sino em torno do personagem
	VSTATE_NEWBUFF62			= 205, // Circulo Dourado, varias explosoes pequenas
	VSTATE_NEWBUFF63			= 206, // Mochila com diamantes roxo nas costas 
	VSTATE_NEWBUFF64			= 207, // Efeito roxo com varias bolhas subindo
	VSTATE_NEWBUFF65			= 208, // Espada com efeito circular
	VSTATE_NEWBUFF66			= 209, // Circulo Vermelho no chao
	VSTATE_NEWBUFF67			= 210, // Circulo Azul no chao
	VSTATE_NEWBUFF68			= 211, // Circulo Amarelo no chao
	VSTATE_NEWBUFF69			= 212, // N/A
	VSTATE_NEWBUFF70			= 213, // N/A
	VSTATE_NEWBUFF71			= 214, // Efeito amarelo ao redor do personagem igual super sayadin
	VSTATE_NEWBUFF72			= 215, // Efeito amarelo ao redor do personagem igual super sayadin (Comeia)
	VSTATE_NEWBUFF73			= 216, // Efeito azul subindo no personagem
	VSTATE_NEWBUFF74			= 217, // Bola de Cristal ao redor do personagem
	VSTATE_NEWBUFF75			= 218, // Efeito verde no personagem ao retor e circulo no chao
	VSTATE_NEWBUFF76			= 219, // Efeito Chines gigante ao redor
	VSTATE_NEWBUFF77			= 220, // Efeito no chao amarelo/terra com uns raios expandindo
	VSTATE_NEWBUFF78			= 221, // Efeito no chao azul com uns raios entrando
	VSTATE_NEWBUFF79			= 222, // Efeito amarelo (bola) que some
	VSTATE_NEWBUFF80			= 223, // N/A
	VSTATE_NEWBUFF81			= 224, // N/A
	VSTATE_NEWBUFF82			= 225, // Samurai preto gigante sumindo
	VSTATE_NEWBUFF83			= 226, // Lua gigante sumindo
	VSTATE_NEWBUFF84			= 227, // Efeito verde sumindo
	VSTATE_NEWBUFF85			= 228, // Efeito azul sumindo
	VSTATE_NEWBUFF86			= 229, // Efeito vermelho no chao rodando
	VSTATE_NEWBUFF87			= 230, // Efeito amarelo no chao rodando
	VSTATE_NEWBUFF88			= 231, // Efeito azul no chao rodando
	VSTATE_NEWBUFF89			= 232, // Efeito laranja no chao rodando
	VSTATE_NEWBUFF90			= 233, // Efeito rosa no chao rodando
	VSTATE_NEWBUFF91			= 234, // Efeito verde no chao rodando
	VSTATE_NEWBUFF92			= 235, // N/A
	VSTATE_NEWBUFF93			= 236, // Efeito do Novo escudo do Mago
	VSTATE_NEWBUFF94			= 237, // Chines comendo peixe no ombro
	VSTATE_NEWBUFF95			= 238, // Chines comendo sopa no ombro
	VSTATE_NEWBUFF96			= 239, // Chines comendo sei la o que no ombro
	VSTATE_NEWBUFF97			= 240, // N/A
	VSTATE_NEWBUFF98			= 241, // Efeito bola verde rodiando o personagem
	VSTATE_NEWBUFF99			= 242, // Efeito terra rodiando o personagem
	VSTATE_NEWBUFF100			= 243, // Efeito do Macaco quando imune
	VSTATE_NEWBUFF101			= 244, // Marca 01 Andarilho
	VSTATE_NEWBUFF102			= 245, // Marca 02 Andarilho
	VSTATE_NEWBUFF103			= 246, // Marca 03 Andarilho
	VSTATE_NEWBUFF104			= 247, // Marca 04 Andarilho
	VSTATE_NEWBUFF105			= 249, // Efeito Yin Andarilho
	VSTATE_NEWBUFF106			= 248, // Efeito Yang Andarilho
	VSTATE_NEWBUFF107			= 250, // Anel amarelo rodando
	VSTATE_NEWBUFF108			= 251, // Efeito de Pedra ( Imunidade do Andarilho )
	VSTATE_NEWBUFF109			= 252, // N/A
	VSTATE_NEWBUFF110			= 253, // N/A
	VSTATE_NEWBUFF111			= 254, // N/A
	VSTATE_NEWBUFF112			= 255, // N/A
	VSTATE_NEWBUFF113			= 256, // N/A
	VSTATE_NEWBUFF114			= 257, // N/A
	VSTATE_NEWBUFF115			= 258, // N/A
	VSTATE_NEWBUFF116			= 259, // N/A 
	VSTATE_NEWBUFF117			= 260, // N/A
	VSTATE_NEWBUFF118			= 261, // N/A
	VSTATE_NEWBUFF119			= 262, // N/A
	VSTATE_NEWBUFF120			= 263, // N/A
	VSTATE_NEWBUFF121			= 264, // N/A
	VSTATE_NEWBUFF122			= 265, //
	VSTATE_NEWBUFF123			= 266, // Madeira
	VSTATE_NEWBUFF124			= 267, // Agua
	VSTATE_NEWBUFF125			= 268, // Metal
	VSTATE_NEWBUFF126			= 269, // Fogo
	VSTATE_NEWBUFF127			= 270, // Terra
	VSTATE_NEWBUFF128			= 271, //
	VSTATE_NEWBUFF129			= 272, //
	VSTATE_NEWBUFF130			= 273, //
	VSTATE_NEWBUFF131			= 274, //
	VSTATE_NEWBUFF132			= 275, //
	VSTATE_NEWBUFF133			= 276, //
	VSTATE_NEWBUFF134			= 277, //
	VSTATE_NEWBUFF135			= 278, //
	VSTATE_NEWBUFF136			= 279, //
	VSTATE_NEWBUFF137			= 280, //
	VSTATE_NEWBUFF138			= 281, //
	VSTATE_TEAMRED				= 284, //
	VSTATE_TEAMBLUE				= 285, //
		
	VSTATE_MAX = 288,
};

enum hidden_state{
	
	HSTATE_DIZZY         				= 1  , // "Оглушение Персонаж не может двигаться, атаковать и использовать навыки."
	HSTATE_SLEEP         				= 2  , // "Сон Не может двигаться, атаковать и использовать навыки. Эффект снимается при атаке на персонажа."
	HSTATE_SLOW          				= 3  , // "Замедление Снижена скорость передвижения."
	HSTATE_RETORT        				= 4  , // "Отражение Отражает урон, наносимый персонажу в ближнем бою."
	HSTATE_FEATHERSHIELD 				= 5  , // "Преграда из перьев Магический щит поглощает физический урон."
	HSTATE_FIRESHIELD    				= 6  , // "Огненный доспех Увеличивает защиту от огня и ускоряет восстановление жизненных сил."
	HSTATE_ICESHIELD     				= 7  , // "Ледяной доспех Увеличивает защиту от воды и ускоряет восстановление магической энергии."
	HSTATE_FIX           				= 8  , // "Обездвиживание Лишает возможности двигаться."
	HSTATE_SEALED        				= 9  , // "Печать Лишает возможности атаковать и использовать умения."
	HSTATE_BLIND         				= 10 , // "Зачаровать Цель становится пассивной."
	HSTATE_SOILSHIELD    				= 11 , // "Земляной доспех Увеличивает защиту от земли и физического урона."
	HSTATE_THUNDER       				= 12 , // "Шок Некоторое время наносит небольшой урон от металла."
	HSTATE_TOXIC         				= 13 , // "Яд Некоторое время наносит небольшой древесный урон."
	HSTATE_BURNING       				= 14 , // "Ожог Некоторое время наносит небольшой урон огнем."
	HSTATE_FALLEN        				= 15 , // "Зыбучий песок Некоторое время наносит небольшой урон земли."
	HSTATE_MAGICLEAK     				= 16 , // "Магический ожог Некоторое время отнимает единицы магической энергии"
	HSTATE_BLEEDING      				= 17 , // "Кровотечение Некоторое время отнимает единицы жизненной силы"
	HSTATE_DECDEFENCE    				= 18 , // "Разрыв Снижает физическую защиту."
	HSTATE_DECRESIST     				= 19 , // "Слабость Снижает магическую защиту."
	HSTATE_DECATTACK     				= 20 , // "Неповоротливость Уменьшает силу физических атак."
	HSTATE_INCHURT       				= 21 , // "Проклятье Увеличивает получаемый урон"
	HSTATE_SLOWATTACK    				= 22 , // "Лень Уменьшает скорость атаки"
	HSTATE_SLOWPRAY      				= 23 , // "Притупление Увеличивает время подготовки умений."
	HSTATE_DECACCURACY   				= 24 , // "Слепота Уменьшает вероятность успешной атаки"
	HSTATE_DECDODGE      				= 25 , // "Неуклюжесть Уменьшает шанс уклонения."
	HSTATE_FASTHPGEN     				= 26 , // "Ускоренная регенерация жизненных сил"
	HSTATE_FASTMPGEN     				= 27 , // "Ускоренная регенерация магической энергии"
	HSTATE_INCHP         				= 28 , // "Рев главы стаи Увеличивает максимальный запас ЖС"
	HSTATE_INCMP         				= 29 , // "Увеличение максимального значения МЭ"
	HSTATE_INCDEFENCE    				= 30 , // "Железный покров Физическая защита повышена."
	HSTATE_INCRESIST     				= 31 , // "Опека духов Увеличивает магическую защиту"
	HSTATE_INCATTACK     				= 32 , // "Крепкий кулак Увеличивает силу физической атаки."
	HSTATE_FASTATTACK    				= 33 , // "Ловкость Увеличивает скорость атаки."
	HSTATE_INCDODGE      				= 34 , // "Внимание Увеличивает шанс уклонения."
	HSTATE_DECHURT       				= 35 , // "Завеса тьмы Уменьшает получаемый урон"
	HSTATE_INCACCURACY   				= 36 , // "Точность Повышает вероятность успешной атаки"
	HSTATE_FASTPRAY      				= 37 , // "Фокусировка Уменьшает время на сотворение заклинания"
	HSTATE_ICEBLADE      				= 38 , // "Ледяное оружие Все атаки наносят дополнительный урон стихией воды."
	HSTATE_FIREBLADE     				= 39 , // "Горящее оружие Все атаки наносят дополнительный урон стихией огня."
	HSTATE_TOXICBLADE    				= 40 , // "Отравленное оружие Все атаки наносят дополнительный древесный урон."
	HSTATE_HPGEN         				= 41 , // "Лечение Некоторое время восстанавливает ЖС"
	HSTATE_MPGEN         				= 42 , // "Созерцание Некоторое время восстанавливает МЭ"
	HSTATE_DECMAGIC      				= 43 , // "Рассеянный дух Уменьшает силу магических атак"
	HSTATE_SPEEDUP       				= 44 , // "Бег Увеличивает скорость"
	HSTATE_DECHP         				= 45 , // "Уменьшает максимальное количество ЖС"
	HSTATE_INCMAGIC      				= 46 , // "Воодушевление Увеличивает магическую атаку"
	HSTATE_TIGERFORM     				= 47 , // "Превращение в оборотня"
	HSTATE_ENHANCEGOLD   				= 48 , // "Повышает защиту от стихии металла"
	HSTATE_ENHANCEWOOD   				= 49 , // "Повышает защиту от стихии дерева"
	HSTATE_ENHANCEWATER  				= 50 , // "Повышает защиту от стихии воды"
	HSTATE_ENHANCEFIRE   				= 51 , // "Повышает защиту от стихии огня"
	HSTATE_ENHANCESOIL   				= 52 , // "Повышает защиту от стихии земли"
	HSTATE_REDUCEGOLD    				= 53 , // "Снижает защиту от стихии металла"
	HSTATE_REDUCEWOOD    				= 54 , // "Снижает защиту от стихии дерева"
	HSTATE_REDUCEWATER   				= 55 , // "Снижает защиту от стихии воды"
	HSTATE_REDUCEFIRE    				= 56 , // "Снижает защиту от стихии огня"
	HSTATE_REDUCESOIL    				= 57 , // "Снижает защиту от стихии земли"
	HSTATE_ANTIWATER     				= 58 , // "Стойка уклонения от воды Нет необходимости дышать под водой. Нельзя использовать умения."
	HSTATE_PANRUO        				= 59 , // "Сутра о душе"
	HSTATE_POWERUP       				= 60 , // "Всплеск Ци Волна энергии укрепляющая стойкость тела"
	HSTATE_XISUI         				= 61 , // "Сутра о внешнем Физическая защита увеличена, магическая защита снижена."
	HSTATE_YIJIN         				= 62 , // "Сутра о внутреннем Магическая защита увеличена, физическая защита снижена."
	HSTATE_APGEN         				= 63 , // "Неистовство зверя Приносит ци при получении ударов."
	HSTATE_STONESKIN     				= 64 , // "Железный покров Физическая защита повышена."
	HSTATE_IRONSHIELD    				= 65 , // "Аура стали Защита увеличена."
	HSTATE_GIANT         				= 66 , // "Невероятная сила Увеличивает физическую атаку."
	HSTATE_DEVILSTATE    				= 67 , // "Кипящая кровь Снижает максимальный запас ЖС, повышает меткость."
	HSTATE_BLESSMAGIC    				= 68 , // "Воодушевление Увеличивает магическую атаку"
	HSTATE_WINGSHIELD    				= 69 , // "Крылатый щит Магическая энергия принимает урон на себя."
	HSTATE_FIREARROW     				= 70 , // "Пылающая стрела Все атаки наносят дополнительный урон огнем"
	HSTATE_EAGLECURSE    				= 71 , // "Когти небес Некоторое время наносит урон металлом и замедляет движение."
	HSTATE_FREEMOVE      				= 72 , // "Бег без препятствий Дает иммунитет ко всем эффектам, затрудняющим передвижение"
	HSTATE_FROZEN        				= 73 , // "Длительный ледяной урон"
	HSTATE_INCSMITE      				= 74 , // "Невероятное проворство Увеличивает шанс критического удара."
	HSTATE_FOXFORM       				= 75 , // "Превращение друида"
	HSTATE_INVINCIBLE    				= 76 , // "Защищает от повреждений"
	HSTATE_JINGJI        				= 77 , // "Барьер шипов Уменьшает получаемый урон и отражает его часть на атакующего."
	HSTATE_NOREGAIN      				= 78 , // "Слабость Жизненные силы и магическая энергия не восстанавливаются."
	HSTATE_CANTI         				= 79 , // "Уязвимость Получаемый урон увеличен."
	HSTATE_APLEAK        				= 80 , // "Истощение При получении каждого удара персонаж теряет ци."
	HSTATE_SWIFTFORM     				= 81 , // "Наряд из цветов Увеличивает скорость передвижения."
	HSTATE_FASTRIDE      				= 82 , // "Увеличивает скорость перемещения питомца"
	HSTATE_SHARPBLADE    				= 83 , // "Увеличивает силу физической атаки"
	HSTATE_IMMUNESEALED					= 84 , // "Концентрация Иммунитет к наложению печати."
	HSTATE_IMMUNESLEEP					= 85 , // "Возбуждение Возбужденный человек в отдыхе не нуждается Иммунитет ко сну."
	HSTATE_IMMUNESLOWDIZZY				= 86 , // "Свобода До тех пор, пока ваше сердце свободно, вы не сможете замедлиться или усилиться. Иммунитет к замедлению скорости движения."
	HSTATE_IMMUNEWOUND					= 87 , // "Усиление Освобождение от труда охлаждает кровь. Сильного человека победить невозможно."
	HSTATE_IMMUNEALL					= 88 , // "Благословение Иммунитет к негативным эффектам."
	HSTATE_IMMUNEPHYSICAL				= 89 , // "Каменное тело Иммунитет к физическому урону."
	HSTATE_IMMUNEFIRE					= 90 , // "Сила огня Иммунитет к стихии огня."
	HSTATE_IMMUNEWATER					= 91 , // "Сила воды Иммунитет к стихии воды."
	HSTATE_IMMUNEMETAL					= 92 , // "Сила металла Иммунитет к стихии металла."
	HSTATE_IMMUNEWOOD					= 93 , // "Сила дерева Иммунитет к стихии дерева."
	HSTATE_IMMUNESOIL					= 94 , // "Сила земли Иммунитет к стихии земли."
	HSTATE_IMMUNEMAGICAL				= 95 , // "Сила неба Иммунитет к магическому урону."
	HSTATE_ARROGANT						= 96 , // "Бешенство Иммунитет ко всему."
	HSTATE_SLOWSWIM						= 97 , // "Штиль Замедление скорости плавания."
	HSTATE_FASTSWIM						= 98 , // "Скорость воды Увеличение скорости плавания."
	HSTATE_SLOWFLY						= 99 , // "Затишье Замедленный полет."
	HSTATE_FASTFLY						= 100, // "Скорость ветра Ускоренный полет"
	HSTATE_SLOWRIDE						= 101, // "Изнурение Замедление скорости ездового животного."
	HSTATE_APGENCONT					= 102, // "Взрыв Продолжительное увеличение ци."
	HSTATE_APLEAKCONT					= 103, // "Усталость Постепенное снижение ци."
	HSTATE_INCELFSTR					= 104, // "Сила демона Продолжительное увеличение силы."
	HSTATE_INCELFAGI					= 105, // "Скорость демона Продолжительное увеличение скорости."
	HSTATE_INCDEFENCE2					= 106, // "Лезвие ветра Направляет мощный удар на противника,  одновременно увеличивая вашу защиту. Увеличение собственной физической защиты"
	HSTATE_WEAKELEMENT					= 107, // "Слабый элемент Физическая защита цели увеличивается, магическая - уменьшается"
	HSTATE_DEEPPOISION 					= 108, // "Смертельный яд Увеличивает получаемый урон, можно совмещать с умением Гнев небес."
	HSTATE_ROOTED						= 109, // "Корни Отражает получаемый урон"
	HSTATE_EARTHGUARD					= 110, // "Защита земли Каждые 3 секунды восстанавливает ЖС, уменьшая урон. Уменьшает физическую и магическую атаки."
	HSTATE_FURY							= 111, // "Свирепость Повышает показатель атаки, но снижает физическую и магическую защиту."
	HSTATE_SANDSTORM					= 112, // "Песчаная буря Уменьшает силу удара, замедляет скорость каста."
	HSTATE_HOMEFEELING					= 113, // "Ностальгия Увеличивает скорость движения"
	HSTATE_REDUCEWATER2					= 114, // "Гибель Уменьшает защиту"
	HSTATE_INCSMITE2					= 115, // "Улыбка судьбы Увеличивает шанс нанесения критического удара"
	HSTATE_DECDEFENCE2					= 116, // "Штурм Уменьшает физическую защиту"
	HSTATE_REDUCEFIRE2					= 117, // "Искра Огонь, уменьшающий защиту"
	HSTATE_SLOWATTACKPRAY				= 118, // "Раздражение Уменьшает скорость атаки и увеличивает время произнесения заклинаний."
	HSTATE_BURNING2						= 119, // "Тление Длительный урон огнем"
	HSTATE_BURNINGFEET					= 120, // "Горящая гора Огонь уменьшает защиту и замедляет скорость передвижения"
	HSTATE_HARDENSKIN					= 121, // "Стена Поглощает физический и магический урон, замедляя скорость движения"
	HSTATE_REDUCEGOLD2					= 122, // "Сияющее лезвие Уменьшает защиту"
	HSTATE_LEAFDANCE					= 123, // "Танец листьев Наносит урон кровотечением, уменьшает скорость движения"
	HSTATE_CHARRED						= 124, // "Прижигание Уменьшает атаку и защиту,  немного увеличивая скорость движения"
	HSTATE_VACUUM						= 125, // "Нирвана Скорость атаки замедляется, скорость движения уменьшается. Также уменьшается получаемый урон"
	HSTATE_IMMUNEBLOODING				= 126, // "Повязка Иммунитет к кровотечению"
	HSTATE_ABSORBPHYSICDAMAGE			= 127, // "Треснувший алмаз Поглощает получаемый физический урон"
	HSTATE_ABSORBMAGICDAMAGE			= 128, // "Безграничная сила Поглощает получаемый магический урон"
	HSTATE_RETORTMAGIC					= 129, // "Месть Отражает магический урон"
	HSTATE_WINDSHIELD					= 130, // "Сила ветра Уменьшает получаемый урон, увеличивает скорость физической атаки и защиту."
	HSTATE_AIRSTREAMLOCK				= 131, // "Воздушный узел Останавливает цель, имеет шанс запечатать ее"
	HSTATE_CLOSED						= 132, // "Блокада Запечатывает и дает иммунитет к физическому урону"
	HSTATE_IMMUNEWEAK					= 133, // "Случайность Иммунитет к эффектам, увеличивающим получаемый урон"
	HSTATE_BEFROZEN						= 134, // "Мерзлота Сковывает движения"
	HSTATE_ADDATTACKDEGREE  			= 135, // "Ярость Увеличивает показатель атаки."
	HSTATE_SUBATTACKDEGREE  			= 136, // "Страх Уменьшает показатель атаки."
	HSTATE_ADDDEFENCEDEGREE  			= 137, // "Увеличивает показатель защиты"
	HSTATE_SUBDEFENCEDEGREE  			= 138, // "Уменьшает показатель защиты"
	HSTATE_FALLEN2 						= 139, // "В течение некоторого времени наносит урон стихией земли"
	HSTATE_SEALED2						= 140, // "Изоляция Лишает возможности атаковать и использовать умения."
	HSTATE_FIX2							= 141, // "Обездвиживание Лишает возможности двигаться."
	HSTATE_DECHURT2						= 142, // "Завеса тьмы Уменьшает получаемый урон"
	HSTATE_INCHURT2						= 143, // "Проклятье Увеличивает получаемый урон"
	HSTATE_INCHP2						= 144, // "Рев главы стаи Увеличивает максимальный запас ЖС"
	HSTATE_INCATTACK2					= 145, // "Крепкий кулак Увеличивает силу физической атаки."
	HSTATE_INCMAGIC2					= 146, // "Воодушевление Увеличивает магическую атаку"
	HSTATE_FASTPRAY2					= 147, // "Внимание Уменьшает время подготовки заклинаний."
	HSTATE_SPEEDUP2						= 148, // "Бег Увеличивает скорость"
	HSTATE_INVISIBLE					= 149, // "Исчезновение Цель становится невидимой"
	HSTATE_INCANTIINVISIBLEACTIVE 		= 150, // "Проницательный взгляд Увеличивает уровень обнаружения"
	HSTATE_INCHPSTEAL					= 151, // "Проклятие крови При каждой атаке восстанавливается некоторое количество жизни"
	HSTATE_INCCRITDAMAGE				= 152, // "Бешенство Повышает урон от критических ударов."
	HSTATE_INCDAMAGEDODGE				= 153, // "Дает шанс избежать получения урона"
	HSTATE_INCDEBUFFDODGE				= 154, // "Дает шанс избежать наложения негативных эффектов"
	HSTATE_REBIRTH						= 155, // "Обман смерти Защищает от одного смертельного удара. Восстанавливает ЖС после него."
	HSTATE_SOULRETORT					= 156, // "Возмездие При отскоке наносит повреждения нападавшему"
	HSTATE_SOULSEALED					= 157, // "Печать Накладывает на противника эффект печати"
	HSTATE_SOULBEATBACK					= 158, // "Отражение При применении заставляет противников получать повреждения от собственных атак и попадать под эффект собственных заклинаний"
	HSTATE_SOULSTUN						= 159, // "Трепет Оглушает атакующих противников."
	HSTATE_DEEPENBLESS					= 160, // "Цветение жизни Увеличен эффект лечения навыками и эффект целительных зелий. Сокращено время перезарядки амулета ЖС."
	HSTATE_WEAKENBLESS					= 161, // "Вечное заключение Уменьшен эффект лечения навыками и эффект целительных зелий. Увеличено время перезарядки амулета ЖС."
	HSTATE_HURTWHENUSESKILL				= 162, // "Наносит персонажу урон, если он атакует или применяет навык."
	HSTATE_INTERRUPTWHENUSESKILL 		= 163, // "Использование навыков прекращается Действие каждого произнесенного заклинания прекращается"
	HSTATE_FISHFORM						= 164, // "Превращение в русалку Персонаж находится в облике русалки."
	HSTATE_DEEPICETHRUST				= 165, // "Хладнокровие Скорость атаки понижена, показатель атаки увеличен."
	HSTATE_ADJUSTATTACKDEFEND 			= 166, // "Проклятие шамана Упорядочивает уровень защиты и атаки"
	HSTATE_INCHURTPHYSICGOLD			= 167, // "Алмазное клеймо Увеличивает получаемый физический урон и урон от стихии металла."
	HSTATE_INCHURTWOODWATER 			= 168, // "Морозное клеймо Увеличивает шанс получения критического удара от магии стихии воды и дерева."
	HSTATE_INCHURTFIREEARTH 			= 169, // "Обжигающее клеймо Увеличивает получаемый урон и шанс получения критического удара от магии стихии огня и земли."
	HSTATE_ATTACKATTACHSTATE1 			= 170, // "Техника черного воина При ударе может наложить эффект 'Око черного воина'."
	HSTATE_ATTACKATTACHSTATE2 			= 171, // "Техника кровавого меча При ударе может наложить эффект 'Око кровавого меча'."
	HSTATE_ATTACKATTACHSTATE3 			= 172, // "Техника каменного змея При ударе может наложить эффект 'Око каменного змея'."
	HSTATE_BEATTACKEDATTACHSTATE1 		= 173, // "Око черного воина Усиливает эффект навыка 'Сила ветра'."
	HSTATE_BEATTACKEDATTACHSTATE2 		= 174, // "Око кровавого меча Усиливает эффект навыка 'Удар пустоты'."
	HSTATE_BEATTACKEDATTACHSTATE3 		= 175, // "Око каменного змея Усиливает эффект навыка 'Сила тысячи зверей'."
	HSTATE_BLADESHADOW					= 176, // "Меч сотни теней Наносит урон всем окружающим противникам."
	HSTATE_POISIONSEED					= 177, // "Пары зеленого тумана Если у персонажа останется меньше 60% здоровья, будет наносить урон от стихии дерева."
	HSTATE_HPGENSEED					= 178, // "Облако лепестков При получении урона начинает восстанавливать здоровье"
	HSTATE_INCWOODWATERDEFENSE 			= 179, // "Листва Физическая защита и защита от стихий воды и дерева повышены."
	HSTATE_SPECIALSLOW					= 180, // "Путы плюща Снижение скорости передвижения"
	HSTATE_INCDEFENCESMITE 				= 181, // "Бог войны Повышает физическую защиту и шанс критического удара"
	HSTATE_INCRESISTMAGIC 				= 182, // "Темный демон Повышает уровень защиты пяти стихий и магическую атаку"
	HSTATE_TRANSPORTMPTOPET 			= 183, // "Свет звезд Восстанавливает энергию призванного существа"
	HSTATE_TRANSPORTDAMAGETOPET 		= 184, // "Цветок трех жизней Часть получаемого урона перемещается на питомца."
	HSTATE_ABSORBDAMAGEINCDEFENSE 		= 185, // "Цветок двух жизней Поглощает получаемый урон, повышает физическую и магическую защиту"
	HSTATE_FASTPRAYINCMAGIC 			= 186, // "Быстрая магия Уменьшает время подготовки заклинаний и увеличивает силу магической атаки"
	HSTATE_INCREMENTALHPGEN 			= 187, // "Красный луч солнца Непрерывно восстанавливает ЖС"
	HSTATE_CONSECRATION 				= 188, // "Жертвоприношение Наносит урон стихией огня"
	HSTATE_CHANCEOFREBIRTH				= 189, // "Возрождение Мгновенное возрождение и восстановление ЖС после смерти"
	HSTATE_SPECIALPHYSICHURTTRIGGER		= 190, // "Дьявольское проклятие Удваивает количество наносимого урона при атаке 'Дьявольским проклятием'"
	HSTATE_INCCOUNTEDSMITE				= 191, // "Повышает вероятность критического удара"
	HSTATE_ATTACKATTACHSTATE4 			= 192, // "Техника девяти мечей При ударе может наложить эффект 'Око девяти мечей'."
	HSTATE_BEATTACKEDATTACHSTATE4 		= 193, // "Око девяти мечей Усиливает эффект навыка 'Мощь летящего дракона'."
	HSTATE_WEAPONDISABLED				= 194, // "Слабое оружие Лишает силы оружие цели"
	HSTATE_INCAGGROONDAMAGE 			= 195, // "Увеличение ненависти Во время атаки персонаж накапливает большое количество враждебности"
	HSTATE_ENHANCESKILLDAMAGE 			= 196, // "Благословение Умения, направленные против монстров, наносят двойной урон"
	HSTATE_DETECTINVISIBLE				= 197, // "Эффект невидимости исчезает"
	HSTATE_FASTMPGEN2     				= 198, // "Скорость восстановления магической энергии значительно увеличивается"
	HSTATE_POSITIONROLLBACK				= 199, // "Возвращает в определенную точку через некоторое время."
	HSTATE_HPROLLBACK					= 200, // "Восстанавливает ЖС до определенного значения через некоторое время."
	HSTATE_NOFLY						= 201, // "Тяжесть Полет невозможен."
	HSTATE_NOCHANGESELECT				= 202, // "Помешательство Может атаковать только определенную цель."
	HSTATE_HEALABSORB					= 203, // "Поглощает получаемое лечение."
	HSTATE_REPELONNORMALATTACK			= 204, // "Мистический свет"
	HSTATE_INCCRITRESISTANCE			= 205, // "Крепкий орешек Уменьшает шанс получить критический удар."
	HSTATE_DECCRITRESISTANCE			= 206, // "Беззащитность Увеличивает шанс получить критический удар."
	HSTATE_TRANSMITSKILLATTACK			= 207, // "Крепкая связь Весь урон и негативные эффекты переносятся на применившего заклинание."
	HSTATE_ADDITIONALHEAL				= 208, // "Применяя целительные заклинания, персонаж также будет восстанавливать ЖС."
	HSTATE_ADDITIONALATTACK				= 209, // "Смертельная связь"
	HSTATE_TRANSPORTDAMAGETOLEADER 		= 210, // "Восстанавливает ЖС до определенного значения через некоторое время."
	HSTATE_FORBIDBESELECTED				= 211, // "Не может быть выбранным в качестве цели."
	HSTATE_ENHANCESKILLDAMAGE2			= 212, // "Цветочный вихрь Повышает урон, наносимый навыками. Сочетается с благословениями."
	HSTATE_DELAYEARTHHURT				= 213, // "Наносит урон от стихии земли через некоторое время."
	HSTATE_DIZZYINCHURT					= 214, // "Ледяной мир"
	HSTATE_SOULRETORT2					= 215, // "Пламенная преграда Возвращает физический урон атакующим."
	HSTATE_FIXONDAMAGE					= 216, // "Получая удар, противник может быть обездвижен."
	HSTATE_APGEN2						= 217,
	HSTATE_INCATTACK3					= 218, // "Сила атаки повышена из-за полученного урона."
	HSTATE_INCATTACKONDAMAGE			= 219, // "Адреналин Повышает силу атаки при получении урона."
	HSTATE_REBIRTH2						= 220, // "Второе дыхание При получении смертельного удара персонаж восстановит часть здоровья и снимет все негативные эффекты."
	HSTATE_HEALSTEAL					= 221, // "Звездное пламя Часть эффекта лечения переносится."
	HSTATE_DROPMONEYONDEATH				= 222, // "Отнять и поделить Позволяет выбить из противника предметы, необходимые для заданий поиска драконов"
	HSTATE_INCATTACKRANGE				= 223, // "Увеличивает дальность атаки"
	HSTATE_INVINCIBLE5					= 224, // "Моральная поддержка"
	HSTATE_THUNDERFORM					= 225, // "Ночной танец"
	HSTATE_BLADEAURA					= 226, // "Кара богов"
	HSTATE_YJDANCE						= 227, // "Парный танец"
	HSTATE_DELAYTRANSMIT				= 228,
	HSTATE_DECNORMALATTACKHURT			= 229, // "Снижает входящий урон от обычной атаки в ближнем бою."
	HSTATE_INCATKDEFHP					= 230, // "Повышает атаку, защиту и здоровье персонажа."
	HSTATE_HPMPGENNOTINCOMBAT			= 231, // "В состоянии вне боя здоровье и мана быстро восстанавливаются."
	HSTATE_INCHPMP						= 232, // "Увеличивает здоровье и ману."
	HSTATE_INCHURT3						= 233, // "Получаемый урон увеличивается. Складывается с другими подобными эффектами."
	HSTATE_NONPENALTYPVP				= 234, // "В этом режиме РК невозможно получить красное имя. За убийство соперника нет добычи. В случае смерти опыт не теряется."
	HSTATE_INCRESIST2					= 235, // "Увеличивает магическую защиту"
	HSTATE_FLAGER						= 236, // "Вы несете флаг. Скорость снижена. Полет невозможен. Использование джинна невозможно."
	HSTATE_SUBDEFENCEDEGREE2 			= 237, // "Уменьшает показатель защиты"
	HSTATE_INCATKDEFHP2					= 238, // "Увеличивает здоровье и ману."
	HSTATE_INCSMITE3					= 239, // "Невероятное проворство Увеличивает шанс критического удара."
	HSTATE_INCPENRES					= 240, // "Увеличиваются показатели защиты от монстров и урона по монстрам"
	HSTATE_INCMAXHPATKDFDLEVEL			= 241, // "Повышает урон от навыков и показатель защиты."
	HSTATE_GTAWARD1						= 242, // "Повышает показатель атаки и защиты на 3 ед."
	HSTATE_GTAWARD2						= 243, // "Повышение уровня атаки и защиты"
	HSTATE_DECHURT3						= 244, // "Уменьшает получаемый от игроков урон."
	HSTATE_ATTACHSTATETOSELF			= 245, // "При атаке есть вероятность наложить на себя положительный эффект."
	HSTATE_ATTACHSTATETOTARGET			= 246, // "При атаке есть вероятность наложить на цель негативный эффект."
	HSTATE_IMMUNEPHYSICAL2				= 247, // "Иммунитет к физическому урону."
	HSTATE_IMMUNEMETAL2					= 248, // "Иммунитет к стихии металла."
	HSTATE_IMMUNEWOOD2					= 249, // "Иммунитет к стихии дерева."
	HSTATE_IMMUNEWATER2					= 250, // "Иммунитет к стихии воды"
	HSTATE_IMMUNEFIRE2					= 251, // "Иммунитет к стихии огня."
	HSTATE_IMMUNESOIL2					= 252, // "Иммунитет к стихии земли."
	HSTATE_RETORT2						= 253, // "Отражение Отражает урон, наносимый персонажу в ближнем бою."
	HSTATE_ADDATTACKDEFENDDEGREE		= 254, // "Усиление боевых способностей"
	HSTATE_PALSY						= 255, // "Паралич Лишает возможности двигаться и использовать умения."
	HSTATE_INCHURT4						= 256, // "Податливость Умения наносят персонажу повышенный урон."
	HSTATE_INCBECRITRATE				= 257, // "Повышение вероятности нанесения критического удара при помощи умений"
	HSTATE_MODIFYSPECSKILLPRAY			= 258, // "Уменьшение времени подготовки специальных умений"
	HSTATE_INCSPECSKILLDAMAGE			= 259, // "Увеличение урона от специальных умений"
	HSTATE_ICESHIELD2					= 260, // "Ледяной доспех Увеличивает защиту от воды, ускоряет восстановление магической энергии и восстановление энергии ци."
	HSTATE_FIRESHIELD2					= 261, // "Огненный доспех Увеличивает защиту от огня, ускоряет восстановление здоровья и повышает вероятность критического удара."
	HSTATE_HEALSHIELD					= 262, // "Поглощение большей части урона и длительное восстановление здоровья."
	HSTATE_INCFLYSPEED					= 263, // "Повышение скорости полета Эффект может суммироваться. При повторном использовании время действия обновляется."
	HSTATE_INCVIGOUR					= 264, // "Повышение боевого духа."
	HSTATE_INCVIGOUR2					= 265, // "Повышает боевой дух и уменьшает получаемый крит. урон"
	HSTATE_MOVEPUNISH					= 266, // "Жабий шаг Наносит урон при передвижении. Чем дальше перемещается враг, тем больше урон."
	HSTATE_STANDPUNISH					= 267, // "Наносит урон, если персонаж не находится в движении."
	HSTATE_STANDPUNISH2					= 268, // "Переместившись ближе установленного предела, можно получить особые эффекты"
	HSTATE_CHANTSHIELD					= 269, // "До исчезновения щита - иммунитет к умениям"
	HSTATE_INTERVALPALSY				= 270, // "Лунная отрава Периодическое наложение эффекта паралича"
	HSTATE_INTERNALINJURY				= 271, // "Внутренние повреждения После падения здоровья ниже 25% активируется дополнительный урон"
	HSTATE_ATKDAMAGEREDUCE				= 272, // "Лунная защита Снижает получаемый урон от обычной атаки"
	HSTATE_DEATHRESETCD					= 273, // "После смерти противника 'Азарт' восстанавливается мгновенно"
	HSTATE_APPENDENCHANT				= 274, // "Определенные умения накладывают дополнительные эффекты"
	HSTATE_APPENDDAMAGE					= 275, // "При обычной атаке наносится дополнительный урон"
	HSTATE_COOLDOWNAWARD				= 276, // "Мгновение Некоторые умения можно применять без восстановления"
	HSTATE_HUNTERSOUL					= 277, // "Оскорбление Персонаж получит урон и будет оглушен, если не атакует противника."
    HSTATE_SHADOWFORM           		= 278, // "Тень дракона Повышается скорость атаки, в дальнем бою получаемый урон снижается"
    HSTATE_FAIRYFORM            		= 279, // "Тень дракона Повышаются физическая защита и скорость передвижения, усиливается эффект от некоторых умений"
    HSTATE_ADDFROSTEFFECT       		= 280, // "Некоторое время наносит урон от металла и воды, эффект суммируется до 5 раз"
    HSTATE_MOONGOD              		= 281, // "Благословение луны Снижает получаемый урон и дает иммунитет к отрицательным эффектам, но при этом не действуют эффекты лечения"
    HSTATE_ENHANCESKILLDAMAGE3  		= 282, // "Лунный стих Повышает урон, наносимый умениями. Сочетается с благословениями."
	HSTATE_CRITDAMAGEREDUCE				= 283, // "Лунный стих Снижается входящий крит. урон"
    HSTATE_INCPHYSICALDAMAGE    		= 284, // "Повышается исходящий физ. урон"
    HSTATE_INCMAGICALDAMAGE     		= 285, // "Повышается исходящий маг. урон"
	HSTATE_INCHURT5						= 286, // "Податливость Умения наносят персонажу повышенный урон."
	HSTATE_BLACKWHITE					= 287, 
	HSTATE_COOLDOWNPUNISH				= 288, // "Увеличивает время восстановления следующего примененного умения"
	HSTATE_ANTICLEARBUF					= 289, // "Лунное затмение Иммунитет к снятию положительных эффектов"
	HSTATE_INCENCHANTRANGE				= 290, // "Увеличивается дальность заклинаний и максимальное расстояние действия"
    HSTATE_INCPHYSICALMAGICALDEFENSE	= 291, // "Праздничная церемония Изменяет значения физ. и маг. защиты"
    HSTATE_REDUCEGOLD3          		= 292, // "Сокрушение луны Защита от металла снижается, эффект не снимается"
    HSTATE_REDUCEWATER3         		= 293, // "Сокрушение луны Защита от воды снижается, эффект не снимается"
    HSTATE_GENHPAP              		= 294, // "Клинок жадности При крит. ударе восстанавливается здоровье и ци"
	HSTATE_DETAINDART           		= 295, // "Статус 'Личная безопасность' Запрещено использовать летательные средства, питомцев, режим скрытности, ускорение, возвращение в город. "
    HSTATE_EXTRAEXPFACTOR       		= 296, // "Увеличивает скорость получения опыта, духа и духовного знания."
	HSTATE_WEAKENBLESS2					= 297, // "Проклятие русалки Увеличивает время перезарядки защитных амулетов и идолов"
	HSTATE_SOLO_INCATTACKANDMAGIC   	= 298, // "Увеличивает физическую и магическую атаку"
	HSTATE_SOLO_INCDEFENCE      		= 299, // "Увеличивает физическую защиту"
	HSTATE_SOLO_ENHANCERESIST   		= 300, // "Увеличивает защиту от стихий"
	HSTATE_SOLO_INCMAXHP        		= 301, // "Увеличивает максимум здоровья"
	HSTATE_SOLO_HPGEN           		= 302, // "Восстанавливает здоровье"
	HSTATE_SOLO_DECHURT         		= 303, // "Уменьшает получаемый урон"
	HSTATE_SOLO_ADDATTACKRANGE  		= 304, // "Увеличивает дальность атаки"
	HSTATE_SOLO_INVINCIBLE      		= 305, // "Защищает от повреждений"
	HSTATE_THUNDER3             		= 306, // "Длительный входящий урон от металла"
	HSTATE_TOXIC3               		= 307, // "Длительный входящий урон от дерева"
	HSTATE_FLOOD3						= 308, // "Длительный входящий урон от воды"
	HSTATE_BURNING3             		= 309, // "Длительный входящий урон от огня"
	HSTATE_FALLEN3						= 310, // "В течение некоторого времени наносит урон стихией земли"

//----------------------------------------------------------------------------------------------------------------
//---[154 - 162]--
//----------------------------------------------------------------------------------------------------------------

	HSTATE_INCANTIDEFENSEDEGREE			= 311, // "Повышение физического пробивания"
	HSTATE_INCANTIMAGICDEFENSEDEGREE	= 312, // "Повышение магического пробивания"
	HSTATE_SOLO_ATTACKLEVEL				= 313, // "Ярость Увеличивает показатель атаки."
	HSTATE_SOLO_DEFENSELEVEL			= 314, // "Увеличивает показатель защиты"
	HSTATE_315 							= 315, // "Повышение входящего урона"
	HSTATE_316 							= 316, // "Проклятие На каждом уровне урон от умения повышается на 5%. После 10 уровня наносит игроку смертельный урон"
	HSTATE_317 							= 317, // "Быстрая перезарядка Замедляется при получении урона"
	HSTATE_318 							= 318, // "Снижение урона Уменьшает весь получаемый урон"
	HSTATE_ACCUMULATEATTACK				= 319, // "Дух воина Каждое применение умения, наносящего прямой урон, увеличивает урон от последующего умения. Эффект может суммироваться"
	HSTATE_ACCUMULATEATTACK2			= 320, // "Магическое воплощение Увеличивает наносимый и получаемый урон от умений"
	HSTATE_INCPLUSMAXHP					= 321, // "Божественное перо Восстанавливает здоровье, увеличивает максимальный запас здоровья"
	HSTATE_AURACURSE4ASN				= 322, // "Исчезновение Позволяет стать невидимым на короткое время"
	HSTATE_INCMAGIC4					= 323, // "Поклонение Сила духа переходит в силу магической атаки"
	HSTATE_DECSOUL						= 324, // "Взрыв души Снижение силы духа, увеличение урона"
	HSTATE_GIANTFORM					= 325, // "Меч создателя Увеличение в размерах, иммунитет к ограничению движения, повышение скорости перемещения и силы атаки."
	HSTATE_TRANSDMG2PET					= 326, // "Перенос урона на питомца"
	HSTATE_LOADDMG4MASTER				= 327, // "Проклятие смерти После смерти полученный урон переносится на окружающих врагов"
	HSTATE_DECREGIONDMG					= 328, // "Уменьшает непрямой урон, полученный от всех противников, за исключением игроков"
	HSTATE_DECREGIONDMG2				= 329, // "Уменьшает непрямой урон, полученный от игроков"
	HSTATE_DECFARDMG					= 330, // "Уменьшает прямой урон, полученный с расстояния более 8 м"
	HSTATE_DECPHYSICALMAGICALDEFENSE	= 331, // "Снижает физическую и магическую защиту"
	HSTATE_DECPHYSICALMAGICALDEFENSE2	= 332, // "Снижает физическую и магическую защиту"
	HSTATE_DECHEAL						= 333, // "Снижает эффект восстановления здоровья, вызванный умениями, зельями и амулетами"
	HSTATE_INCSMITEDAMAGE				= 334, // "Повышает шанс критического удара и критический урон"
	HSTATE_FASTPRAY3      				= 335, // "Сокращает время подготовки умений"
	HSTATE_INCDEBUFFDODGE2				= 336, // "При атаке повышает шанс избежать наложения негативного эффекта"
	HSTATE_INCDAMAGEDODGE2				= 337, // "Дает шанс избежать получения урона"
	HSTATE_DEBITHURT2					= 338, // "Божественный щит Поглощает получаемый урон"
	HSTATE_DEBITHURT1					= 339, // "Урон, поглощенный щитом, постепенно переносится на персонажа"
	HSTATE_340 							= 340, // "Персонаж получает урон спустя некоторое время"
	HSTATE_HEALNURSE					= 341, // "Когда здоровье снижается до определенной отметки, снимаются все негативные эффекты, здоровье частично восстанавливается."
	HSTATE_342 							= 342, // "Усиливает атаку и защиту, повышает максимальный запас здоровья."
	HSTATE_343 							= 343, // "Кровопийца При каждой атаке восстанавливается некоторое количество здоровья"
	HSTATE_344 							= 344, // "Особое право платформы Perfect World Повышение боевого духа: чем выше уровень платформы, тем больше прибавка боевого духа"
	HSTATE_345 							= 345, // "Повышение шанса крит. удара от особого умения"
	HSTATE_346 							= 346, // "Повышение уровня атаки"
	HSTATE_347 							= 347, // "Повышение уровня защиты"
	HSTATE_348 							= 348, // "Повышение урона, наносимого монстрам"
	HSTATE_349 							= 349, // "Повышение защиты от монстров"
	HSTATE_350 							= 350, // "Уменьшение расхода ци на особое умение"
	HSTATE_351 							= 351, // "Сохранение наивысшего уровня ненависти"
	HSTATE_ELFLOCK						= 352, // "Блокировка джинна"
	HSTATE_353 							= 353, // "Поглощение получаемого урона"
	HSTATE_354 							= 354, // "Великое око черного воина Для активации необходима Великая мощь яростного медведя"
	HSTATE_355 							= 355, // "Великое око девяти мечей Для активации необходима Великая мощь летящего дракона"
	HSTATE_356 							= 356, // "Великое око каменного змея Для активации необходима Великая сила тысячи зверей"
	HSTATE_357 							= 357, // "Великое око кровавого меча Для активации необходим Великий удар пустоты"
	HSTATE_358 							= 358, // "Повышение прямого урона"
	HSTATE_359 							= 359, // "Уменьшение эффекта восстановления"
	HSTATE_OTHERGOLD  					= 360, // "Длительный урон стихией металла, активируется особым умением"
	HSTATE_OTHERWOOD  					= 361, // "Длительный урон стихией дерева, активируется особым умением"
	HSTATE_OTHERWATER 					= 362, // "Длительный урон стихией воды, активируется особым умением"
	HSTATE_OTHERFIRE  					= 363, // "Длительный урон стихией огня, активируется особым умением"
	HSTATE_OTHERSOIL  					= 364, // "Длительный урон стихией земли, активируется особым умением"
	HSTATE_OTHERRANGE 					= 365, // "Увеличение дальности действия особого умения"
	HSTATE_OTHERDAMAGE 					= 366, // "Увеличение урона от специальных умений"
	HSTATE_OTHERCOOLDOWN 				= 367, // "Мгновение Некоторые умения можно применять без восстановления"
	HSTATE_OTHERPRAYSPEED				= 368, // "Сокращение подготовки особого умения"
	HSTATE_369 							= 369, // "Статус Духа Атака невозможна"
	HSTATE_370 							= 370, // "Замедление Снижена скорость передвижения."
	HSTATE_372 							= 372, // "Помощь богов Снижает некоторые виды особого урона."
	HSTATE_373 							= 373, // "Ускорение В движении скорость нарастает."
	HSTATE_374 							= 374, // "Опьянение Невозможно двигаться по прямой."
	HSTATE_375 							= 375, // "При входящих атаках повышается показатель защиты"
	HSTATE_376 							= 376, // "Повышение показателя защиты"
	HSTATE_377 							= 377, // "Повышает урон от следующей атаки"
	HSTATE_378 							= 378, // "Состязание завершено. Можно получить награду."
	HSTATE_379 							= 379, // "Свидетельство поочередного прохождения точек регистрации."
	HSTATE_380 							= 380, // "Снижение атаки"
	HSTATE_381 							= 381, // "[Гильдия] Ускорение ездового питомца"
	HSTATE_382 							= 382, // "[Гильдия] Повышение урона от умений игрокам"
	HSTATE_383 							= 383, // "[Гильдия] Повышение урона от умений монстрам"
	HSTATE_384 							= 384, // "[Гильдия] Повышение урона от умений монстрам"
	HSTATE_385 							= 385, // "[Гильдия] Ускорение"
	HSTATE_386 							= 386, // "[Гильдия] Снижение входящего урона"
	HSTATE_387 							= 387, // "[Гильдия] Увеличение получаемого опыта, духа и духовного знания"
	HSTATE_GELOATIRADORA				= 388, // "Заморозка Нельзя двигаться и использовать умения."
	HSTATE_389 							= 389, // "Наносит смертельный урон, если суммируется 5 раз."
	HSTATE_390 							= 390, // "Погоня За вами наблюдают!"
	HSTATE_391 							= 391, // "Приговор Если не рассеять эффект, последствия будут ужасны!"
	HSTATE_392 							= 392, // "При атаке связанная цель получает доп. статус"
	HSTATE_393 							= 393, // "Пожирающий вихрь Через 10 сек. соратники в радиусе 20 м получают эффект печати, обезоруживания и пожирающего вихря!"
	HSTATE_395 							= 395, // "Самоподрыв. Наносит смертельный урон окружающим враж. баллистам."
	HSTATE_396 							= 396, // "Делает невидимыми участников отряда вокруг. Время от времени переходит от одного участника к другому. Внимание: каждый участник может удержать ее только один раз."
	HSTATE_397 							= 397, // "Каждые 10 сек. наносимый урон возрастает на 50%. Суммируется до 10 раз для героев и до 50 раз для Древнего аннигилятора и его свиты."
	HSTATE_NEWBUFFSPEED					= 398, // "Благословение от богов-создателей Идеального мира. Повышает скорость перемещения персонажа в любых условиях."
	HSTATE_DISTANCEULTIMATE1			= 399, // "Драконья иллюзия При использовании умений иллюзия копирует их на отмеченную цель."
	HSTATE_DISTANCEULTIMATE2			= 400, // "Жертва иллюзии Иллюзия копирует на эту цель атаки умениями стрелка."
	HSTATE_401 							= 401, // "Кружащиеся птицы Позволяет вернуться на место тени."
	HSTATE_CANNONFORM					= 402, // "Огневая платформа Урон и дальность стрельбы постепенно увеличиваются, но при этом нельзя сдвинуться с места."
	HSTATE_403 							= 403, // "При нескольких следующих атаках восстанавливает ЖС."
	HSTATE_SHATTEREDDREAM				= 404, // "Разбитые мечты Перед каждой атакой мгновенно переносит к текущей цели."
	HSTATE_SHIELDBUFFNEW1				= 406, // "Щит жизни Поглощает урон, дает иммунитет к негативным эффектам."
	HSTATE_SHIELDBUFFNEW2				= 407, // "Щит сердца Весь наносимый урон увеличивается."
	HSTATE_SHIELDBUFFNEW3				= 408, // "Зеркальный щит Отражает негативные эффекты."
	HSTATE_SETICONBUFF1					= 409, // "Весь наносимый урон превращается в физический. Урон от оружия увеличивается."
	HSTATE_SETICONBUFF4					= 410, // "Весь наносимый урон превращается в урон стихией металла. При каждой атаке восстанавливается ци."
	HSTATE_SETICONBUFF2					= 411, // "Весь наносимый урон превращается в урон стихией дерева. При каждой атаке восстанавливается здоровье."
	HSTATE_SETICONBUFF3					= 412, // "Весь наносимый урон превращается в урон стихией воды. При каждой атаке есть шанс заморозить цель."
	HSTATE_SETICONBUFF5					= 413, // "Весь наносимый урон превращается в урон от огня. При каждой атаке у цели отнимается ци."
	HSTATE_SETICONBUFF6					= 414, // "Весь наносимый урон превращается в урон стихией земли. При каждой атаке есть шанс оглушить цель."
	HSTATE_415 							= 415, // "Длительное кровотечение у связанных игроков. Чтобы снять эффект, надо отойти на 25 м."
	HSTATE_416 							= 416, // "При получении лечения игрокам в радиусе 5 м наносится урон, равный лечению."
	HSTATE_417 							= 417, // "Чудесная преграда из перьев Снижает получаемый урон."
	HSTATE_418 							= 418, // "Длительное восстановление ЖС. Могут рассеять только друиды."
	HSTATE_419 							= 419, // "Каждый слой повышает урон Элмсли на 50%."
	HSTATE_420 							= 420, // "Неуязвимость. Эффект может быть снят определенными предметами."
	HSTATE_421 							= 421, // "Продолжительный урон от Силы грома. Если суммируется 8 раз, то наносится смертельный урон."
	HSTATE_422 							= 422, // "Погоня За вами наблюдают!"
	HSTATE_423 							= 423, // "Продолжительный входящий урон стихией металла."
	HSTATE_424 							= 424, // "Хорошее вино можно сделать только из вкусной воды."
	HSTATE_425 							= 425, // "Найдите деревню, наберите воды. Только из деревенской воды получится отличная фэньянская водка."
	HSTATE_426 							= 426, // "При нагревании можно удалить примеси и сделать вино лучше."
	HSTATE_427 							= 427, // "Из зерна можно получить отличное вино."
	HSTATE_428 							= 428, // "Можно забирать вино."
	HSTATE_429 							= 429, // "Благословение танца пламени При следующей атаке особыми умениями критический урон увеличивается."
	HSTATE_430 							= 430, // "Превращение"
	HSTATE_431 							= 431, // "Восстановление ци в небоевом статусе."
	HSTATE_432 							= 432, // "Уменьшается наносимый и получаемый урон."
	HSTATE_433 							= 433, // "Повышается наносимый и получаемый урон."
	HSTATE_434 							= 434, // "Расход маны и восстановление здоровья."
	HSTATE_435 							= 435, // "Снижение урона."
	HSTATE_436 							= 436, // "Иммунитет к урону и негативным эффектам."
	HSTATE_437 							= 437, // "Восстановление здоровья при низком значении ЖС."
	HSTATE_438 							= 438, // "Увеличивается скорость перемещения в небоевом статусе."
	HSTATE_439 							= 439, // "Урон увеличивается при максимуме ЖС."
	HSTATE_440 							= 440, // "Стоп! Не упустите шанс прогнать вредителя!"
	HSTATE_IRAATIRADORA					= 441, // "Получаемый урон от умений увеличивается."
	HSTATE_FEATIRADORA					= 442, // "Праведность Иммунитет ко всем негативным статусам."
	HSTATE_443 							= 443, // "Запускается после входящей обычной атаки. На короткое время дает иммунитет к урону обычных атак."
	HSTATE_REDUCESPEEDDDEBUFF			= 444, // "Боевая позиция Повышает скорость перемещения, снижает получаемый урон, дает уклонение от всех негативных эффектов."
	HSTATE_ULTIPALADIN					= 445, // "Благословение Снижает входящий урон."
	HSTATE_448 							= 448, // "След бабочки"
	HSTATE_449 							= 449, // "Колеблющаяся тень"
	HSTATE_450 							= 450, // "Путь свиньи"

//----------------------------------------------------------------------------------------------------------------
//---[162 - 172]--
//----------------------------------------------------------------------------------------------------------------	
	
	HSTATE_INCATTACKPLUSRECIVE		 	= 451, // "Получаемый урон от умений увеличивается."
	HSTATE_INCATTACKTODEFMF			 	= 452, // "Физическая атака превращается в физ. и маг. защиту"
	HSTATE_INCATTACKMTODEFMF		 	= 453, // "Маг. атака превращается в физ. или маг. защиту"
	HSTATE_INCNEWSHIELDMAGE			 	= 454, // "Волшебный щит Снижает некоторые виды смертельного урона"
	HSTATE_455 							= 455, // "Волшебное убежище Снижает некоторые виды особого урона"
	HSTATE_456 							= 456, // "Статус 'Доставка припасов' Значение статуса может составлять от 1 до 5. "
	HSTATE_457 							= 457, // "Увеличен показатель атаки"
	HSTATE_458 							= 458, // "Увеличен показатель защиты"
	HSTATE_459 							= 459, // "Усиление атаки"
	HSTATE_460 							= 460, // "Восстановление здоровья"
	HSTATE_461 							= 461, // "Повышение макс. здоровья"
	HSTATE_462 							= 462, // "Усиление физ. и маг. защиты"
	HSTATE_464 							= 464, // "Благословение Белой владычицы Снаряжение и карты заменяются на экипировку гвардейцев Белой владычицы. Нажмите, чтобы посмотреть текущее снаряжение."
	HSTATE_465 							= 465, // "Подавление небес Повышает боевой дух и дает иммунитет к любым эффектам от умений других игроков (в том числе союзников), если их уровень небес ниже вашего на 10 и более."
	HSTATE_466 							= 466, // "Благословение вернувшегося героя Доступно персонажам с аккаунтов, не осуществлявших вход в игру с 20 июля 2019 года."
	HSTATE_467 							= 467, // "Война богов и Черного владыки Примите участие в войне на Северном континенте. Когда значение статуса достигнет 10, вы сможете получить награду."
	HSTATE_468 							= 468, // "Статус 'Захват пленников' Убейте требуемую цель, чтобы увеличить значение статуса на 1. "
	HSTATE_469 							= 469, // "Ледяное оружие способно накапливать силу эссенции воды. Нанесите духу воды серьезные раны, чтобы впитать эссенцию."
	HSTATE_470 							= 470, // "Защита титана На некоторое время переносит на защитника весь получаемый урон и негативные эффекты."
	HSTATE_NEWBUFFPALADIN				= 471, // "Яростное лезвие Повышает меткость и шанс критического удара"
	HSTATE_472 							= 472, // "Транспортировка руды Вы несете с собой груз ценной породы"
	HSTATE_473 							= 473, // "Перезарядка защиты титана На некоторое время невозможно повторно получить эффект защиты титана."
	HSTATE_474 							= 474, // "Иммунитет к Призывному рыку На некоторое время дает иммунитет к умению 'Призывной рык'"
	HSTATE_475 							= 475, // "Благословение Долины торосов Благодаря милости Черного владыки все характеристики повышаются"
	HSTATE_477 							= 477, // "Громовой раскат Выдержав десять громовых раскатов, можно призвать духов грома."
	HSTATE_478 							= 478, // "Благословение Долины торосов Благодаря милости богов все характеристики повышаются"
	HSTATE_479 							= 479, // "Вечный лед Ледяное дыхание Севера наносит смертельный урон, если суммируется 3 раза."
	HSTATE_480 							= 480, // "Ярое пламя Яростное пламя Севера наносит смертельный урон, если суммируется 3 раза."
	HSTATE_481 							= 481, // "Свидетельство чемпиона Вы были выбраны для получения награды."
	HSTATE_482 							= 482, // "Сертификат Ледяного штурма После окончания Ледяного штурма достойно сражавшиеся участники получат награду!"
	HSTATE_484 							= 484, // "Битва богов и людей Все характеристики существенно повышаются."
	HSTATE_485 							= 485, // "Эссенция родника"
	HSTATE_NEWBUFFATIRADORA				= 486, // "Атаки наносят дополнительный урон стихией огня."
	HSTATE_487 							= 487, // "Наносит продолжительный суммирующийся урон"
	HSTATE_488 							= 488, // "Яичная скорлупа Есть защита, можно воздействовать только антисептиком."
	HSTATE_489 							= 489, // "Разложение Продолжительное кровотечение."
	HSTATE_490 							= 490, // "Мысленный меч Мгновенное убийство с игнорированием 'Рева меча'."
	HSTATE_491 							= 491, // "Статус 'Сцена' Вы находитесь на сцене."
	HSTATE_492 							= 492, // "Заражение Боец заражен вирусом, требуется дезинфекция."
	HSTATE_493 							= 493, // "Скорлупа Прочная яичная скорлупа, можно очистить антисептиком."
	HSTATE_494 							= 494, // "Свет и тьма: Погибель Повышение исходящего и входящего урона."
	HSTATE_495 							= 495, // "Свет и тьма: Непостоянство При нанесении урона есть шанс убить врага или себя, а также получить эффект снижения урона."
	HSTATE_496 							= 496, // "Свет и тьма: Вращение При нанесении урона этим умением есть шанс удаления времени перезарядки всех умений."
	HSTATE_497 							= 497, // "Свет и тьма: Таинство Ускоренное применение умения."
	HSTATE_498 							= 498, // "Свет и тьма: Эгида Шанс иммунитета к урону."
	HSTATE_499 							= 499, // "Аура меча: Холод Для снятия эффекта нужно найти персонажа с умением 'Аура меча: Жар'."
	HSTATE_500 							= 500, // "Аура Меча: Жар Для снятия эффекта нужно найти персонажа с умением 'Аура меча: Холод'."
	HSTATE_501 							= 501, // "Иная реальность Персонаж попадает в особую реальность, где не может взаимодействовать с другими игроками. "
	HSTATE_502 							= 502, // "Отделение души Чем дольше нахождение в  зоне хаоса, тем слабее получаемое лечение."
	HSTATE_503 							= 503, // "Удар грома Усиление входящего урона стихии грозы."
	HSTATE_504 							= 504, // "Болотный взрыв"
	HSTATE_505 							= 505, // "Статус 'Сфера грома'"
	HSTATE_506 							= 506, // "Парализующий токсин Токсин черной дыры приводит к параличу нервной системы."
	HSTATE_507 							= 507, // "Иммунитет к ядам"
	HSTATE_508 							= 508, // "Иммунитет к обездвиживанию"
	HSTATE_509 							= 509, // "Яд ликориса Столб зеленого света вокруг танцовщицы: -1 слой. Столб синего света вокруг танцовщицы: -2 слоя. Столб розового света вокруг танцовщицы: -3 слоя."
	HSTATE_510 							= 510, // "Яд цветка Полночной вечности Попав в тело, яд наносит продолжительный урон. Для нейтрализации нужно подойти к голубому цветку вечности."
	HSTATE_519 							= 519, // "Фатальная расправа На некоторое время дает бессмертие и иммунитет к ограничению движения."
	HSTATE_520 							= 520, // "Фатальная расправа перестает действовать."
	HSTATE_521 							= 521, // "Повышает критический урон."
	HSTATE_522 							= 522, // "Если рядом менее двух врагов, наносимый урон повышается."
	HSTATE_523 							= 523, // "Щит от урона Во время существования щита восстанавливается здоровье."
	HSTATE_524 							= 524, // "Щит от урона"
	HSTATE_525 							= 525, // "Кровавая расправа Ускоряет, усиливает эффекты некоторых умений."
	HSTATE_526 							= 526, // "Кровожадность После накопления 5 слоев взрывается и наносит остаточный урон."
	HSTATE_527 							= 527, // "Застывание Замедляет, при входящей атаке 'Ударом холода' могут возникнуть доп. эффекты."
	HSTATE_528 							= 528, // "Щит от урона При входящей атаке атакующий получает эффект застывания."
	HSTATE_529 							= 529, // "Эффект иммунитета для окружающих союзников на определенное время."
	HSTATE_530 							= 530, // "Потерянное здоровье повышает атаку."
	HSTATE_531 							= 531, // "Приблизьтесь к персонажу с тем же магнитным полюсом, чтобы на короткое время получить силу грома!"
	HSTATE_532 							= 532, // "Круг красного цвета. В сочетании с желтым он становится оранжевым, в сочетании с синим - фиолетовым. "
	HSTATE_533 							= 533, // "Круг желтого цвета. В сочетании с красным он становится оранжевым, в сочетании с синим - зеленым. Через 45 сек. после появления превращается в красный, желтый или синий круг."
	HSTATE_534 							= 534, // "Круг синего цвета. В сочетании с желтым он становится зеленым, в сочетании с красным - фиолетовым. Через 45 сек. после появления превращается в красный, желтый или синий круг."
	HSTATE_535 							= 535, // "Круг оранжевого цвета. В сочетании с другими кругами не меняется. Через 45 сек. после появления превращается в красный, желтый или синий круг."
	HSTATE_536 							= 536, // "Круг фиолетового цвета. В сочетании с другими кругами не меняется. Через 45 сек. после появления превращается в красный, желтый или синий круг."
	HSTATE_537 							= 537, // "Круг зеленого цвета. В сочетании с другими кругами не меняется. Через 45 сек. после появления превращается в красный, желтый или синий круг."
	HSTATE_538 							= 538, // "Контроль духа Если значение статуса достигнет 10, вы не сможете противостоять Аиде."
	HSTATE_541 							= 541, // "Ветер защиты Уменьшает получаемый урон пропорционально дистанции, с которой он нанесен."
	HSTATE_542 							= 542, // "Повышает наносимый урон по монстрам"
	HSTATE_543 							= 543, // "Увеличение потребляемой энергии ци при использовании умений"
	HSTATE_544 							= 544, // "Подвергнувшись атаке, можно испытать эффект оглушения."
	HSTATE_553 							= 553, // "Доспех правителя Увеличивает физическую защиту, защиту от стихий воды, огня, земли, а также дает продолжительное восстановление ци и повышает шанс крит. удара"
	HSTATE_545 							= 545, // "Потеря шлема Характеристики и способности, получаемые от надетого шлема, временно утрачиваются"
	HSTATE_546 							= 546, // "Продолжительное восстановление оч. комбо"
	HSTATE_547 							= 547, // "Новичок Позволяет участвовать в событии 'Путь новичка'."
	HSTATE_548 							= 548, // "Увеличение скорости получения опыта и духа (включая опыт и дух, полученные как трофей и за выполнение заданий) Прекращается после 2-го перерождения ур. 100."
	HSTATE_549 							= 549, // "Увеличение скорости получения духовного знания (включая духовное знание, полученное как трофей и за выполнение заданий) "
	HSTATE_550 							= 550, // "Концентрация духа Повышает силу духа."
	HSTATE_551 							= 551, // "После смерти противника 'Меч императора' восстанавливается мгновенно"
	HSTATE_552 							= 552, // "Облако лепестков После получения урона увеличивает защиту."
	HSTATE_ARMORAPEX					= 553, // Armadura Apex
	HSTATE_554 							= 554, // "Запрещает применять умения перемещения"
	HSTATE_REDUCEDISTANCEATK			= 555, // "Уменьшает урон от дальних атак"
	HSTATE_MONKEYFORM					= 556, // "Превращение странника"
	HSTATE_NAOPODESAIRDOLOCAL			= 557, // "Не позволяет выйти за границы круга"
	HSTATE_ULTIMATEMONKEY				= 558, // "Наследие предков Позволяет свободно использовать умения человеческого облика"
	HSTATE_EVITAOPROXIMOEFEITO			= 559, // "Позволяет уклоняться от урона или негативных эффектов"
	HSTATE_SHATTEREDDREAMMONKEY 		= 560, // "При следующей атаке перемещает вперед"
	HSTATE_BLOQUEIADANOSDIRETOS			= 561, // "Широкое небо Уменьшает прямой урон"
	HSTATE_BLOQUEIAVELOCIDADEVALORFIXO	= 562, // "Фиксирует заданную скорость, не позволяет ускоряться"
	
	
//----------------------------------------------------------------------------------------------------------------
//---[172+ NEW FILTER 10k+]--
//----------------------------------------------------------------------------------------------------------------
	
	HSTATE_10000 						= 10000, // "Значок для вставки_Блик Собрав 10 000 значков, их можно использовать в наборе особых статусов."
	HSTATE_10001 						= 10001, // "Статус 'Представление' Бойца приглашают участвовать в представлении на Камне грез."
	HSTATE_10002 						= 10002, // "Аура мысленного меча Этот эффект дает комбинация умений 'Аура меча: Холод' и 'Аура меча: Жар'."
	HSTATE_10003 						= 10003, // "Ненависть, излучаемая духами, наносит продолжительный урон. Держитесь от них подальше!"
	HSTATE_10004 						= 10004, // "Взрыв силы Бездушных!"
	HSTATE_10005 						= 10005, // "Скрывайтесь от патрульных, чтобы не получить смертельный урон."
	HSTATE_10006 						= 10006, // "Усиление урона Дает прибавку входящего урона, с каждым слоем эффект усиливается, после накопления 10 слоев возникает непреодолимая слабость."
	HSTATE_10007 						= 10007, // "Положительный полюс Держитесь подальше от игроков с отрицательным магнитным полюсом, чтобы не получить большой дополнительный урон!"
	HSTATE_10008 						= 10008, // "Отрицательный полюс Держитесь подальше от игроков с положительным магнитным полюсом, чтобы не получить большой дополнительный урон!"
	HSTATE_10009 						= 10009, // "Входящий урон от следующего 'Раздирания души' повышен."
	HSTATE_10010 						= 10010, // "Мощная сила притяжения преграждает путь!"
	HSTATE_10011 						= 10011, // "Статус 'Сопровождение' Запрещено использовать летательные средства, ездовых питомцев, режим скрытности, ускорение, умения возвращения в город."
	HSTATE_10012 						= 10012, // "Повышение урона, после накопления 5 слоев - значительное повышение урона."
	HSTATE_10013 						= 10013, // "Какая-то мистическая сила препятствует вашему полету."
	HSTATE_10014 						= 10014, // "Запрет входа в Ледяной город Ограничение теряет силу после выполнения задания 'Первая достигнутая цель' сюжетной линии Ледяного города. "
	HSTATE_10015 						= 10015, // "Дуэль могучих Попробуйте выжить!"
	HSTATE_10016 						= 10016, // "Круг смерти Площадь отрешения окружена смертоносным туманом, который при вдыхании вызывает продолжительное кровотечение."
	HSTATE_10017 						= 10017, // "Восхитительное вино Прекрасное вино, вызывающее у выпившего радость и повышающее наносимый урон."
	HSTATE_10018 						= 10018, // "Физическая сопротивляемость Молайн входит в резонанс с каменной статуей, уменьшается получаемый физический урон."
	HSTATE_10019 						= 10019, // "Магическая сопротивляемость Молайн входит в резонанс с каменной статуей, уменьшается получаемый магический урон."
	HSTATE_10020 						= 10020, // "Чаша вина Следите, чтобы у вас было не более 2 чаш, иначе получите смертрельный урон во время Тоста полководца. Не пейте много! "
	HSTATE_10022 						= 10022, // "Ослабление души Атаки Байли Фэнцзяна в ближнем бою для вас крайне опасны!"
	HSTATE_10023 						= 10023, // "Золотые колокольчики Байли Чжишуя Звук колокольчиков привлекает внимание Байли Фэнцзяна."
	HSTATE_10024 						= 10024, // "Разделение души После спадения статуса у вас под ногами образуется разрушенное пространство."
	HSTATE_10025 						= 10025, // "Внутреннее повреждение Наносит дополнительный урон при получении удара от Байли Фэнцзяна в ближнем бою. При накоплении 7 слоев Пробивающая ладонь наносит смертельный урон."
	HSTATE_10026 						= 10026, // "Невозможно получить эффект снижения урона 'Боевая одержимость'."
	HSTATE_10027 						= 10027, // "Счастливый молоток Этим молотком, приносящим удачу, можно легко разбить золотого быка в саду Чунь Сюе."
	HSTATE_MARCADOVENTO					= 10028, // "Печать ветра Особая техника странников. Одна из четырех печатей, образующих 'Кольцо стихий'. Замкнув кольцо, можно сковать врага."
	HSTATE_MARCADAFLORESTA				= 10029, // "Печать леса  Особая техника странников. Одна из четырех печатей, образующих 'Кольцо стихий'. Замкнув кольцо, можно сковать врага."
	HSTATE_MARCADOFOGO					= 10030, // "Печать огня  Особая техника странников. Одна из четырех печатей, образующих 'Кольцо стихий'. Замкнув кольцо, можно сковать врага."
	HSTATE_MARCADAMONTANHA				= 10031, // "Печать горы  Особая техника странников. Одна из четырех печатей, образующих 'Кольцо стихий'. Замкнув кольцо, можно сковать врага."
	HSTATE_MARCAYIN						= 10032, // "Знак 'Инь' Особая техника странников. Если собрать энергию инь и ян, некоторые умения получат особый эффект."
	HSTATE_MARCAYANG					= 10033, // "Знак 'Ян' Особая техника странников. Если собрать энергию инь и ян, некоторые умения получат особый эффект."
	HSTATE_MOVIMENTODASMAOS				= 10034, // "Особая защита войска Бездушных. Чтобы избавиться от нее, требуется Жетон генерала."
	HSTATE_COMBOMARCAPINCEL				= 10035, // "Запретный круг Не позволяет выйти за границы круга"
	HSTATE_MONTANHAVERDADEIRA			= 10036, // "Каменное сердце Обращает в камень, вводит в состояние неуязвимости"
	
};

#define IMMUNEPHYSICAL 0x00000001   //????????????
#define IMMUNEMETAL    0x00000002   //??????
#define IMMUNEWOOD     0x00000004   //????l?
#define IMMUNEWATER    0x00000008   //??????
#define IMMUNEFIRE     0x00000010   //??????
#define IMMUNESOIL     0x00000020   //???????
#define IMMUNEDIZZY    0x00000040   //???????
#define IMMUNESLEEP    0x00000080   //???????
#define IMMUNESLOW     0x00000100   //???????
#define IMMUNEFIX      0x00000200   //???????
#define IMMUNECURSED   0x00000400   //?????????????????
#define IMMUNEWEAK     0x00000800   //??????????
#define IMMUNEREPEL    0x00001000   //???????
#define IMMUNEWOUND    0x00002000   //????HP?????????????????HP
#define IMMUNEBREAK    0x00004000   //???????jsession
#define IMMUNEDIRECT   0x00008000   //????behurt
#define IMMUNECLEAR    0x00010000   //???????filter
#define IMMUNEBLOODING 0x00020000	//???????			lgc
#define IMMUNEALL	   0x00040000	//???????и?????
#define IMMUNEDROP	   0x00080000	//??????????????
#define IMMUNEPALSY	   0x00100000   //???????

enum
{
	MULTIOBJ_EFFECT_HEAL,
	MULTIOBJ_EFFECT_ATTACK,
	MULTIOBJ_EFFECT_ATTACK2,
};

enum
{
	STIME_GFX_MOVEPUNISH = 1,
	STIME_GFX_INTERNALINJURY,
	STIME_GFX_HUNTERSOUL,
};

}

#endif
